---
title: "CNBC"
author: "Steven Kang"
format: html
editor: source
vignette: >
  %\VignetteIndexEntry{Reuters}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
---

# Find corporation names in messy website text with inconsistent name formats of the latest CNBC business news headlines

## load packages

```{r}
#| include: false
devtools::load_all(".")

knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>"
)

```

```{r, message=FALSE}
library(corporations)
```

This vignette also uses `rvest`.

```{r}
library(rvest) # for web scraping 
```

## Corporations Mentioned on the CNBC business page

Using `rvest` we scrape the cnbc.com and get all linked stories.  

```{r}
html <- read_html("https://www.cnbc.com/business/") # The CNBC Business page
links <- html_nodes(html, "a") # "a" nodes are linked text

cnbc <- html_text(links)

cnbc[138:150]
```

```{r}
# Load the data as a tibble (dataframe)
cnbc_df <- data.frame(headline = cnbc, stringsAsFactors = FALSE)

# Run the extract function
# Note: we tell the function to look in the "headline" column
results <- extract(
  data = cnbc_df,
  col_name = "headline",
  verbose = TRUE
 )

head(results)
```


